# Composite Action : https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# GitHub Action의 Compsite 액션 지정하기 : https://blog.outsider.ne.kr/1592
# GitHub Workflow 재사용하기 : https://marshallku.com/dev/reuse-github-actions
name: PR Generator

# Requirements : 아래 권한 추가 필요
# workflow.yaml# .job.[job-id].permissions에 아래 권한 추가

input:
  dest_branch:
    description: "PR의 목적지"
    required: true

  github_token:
    description: "{{ .github.token }} 필요"
    required: true

runs:
  using: composite
  steps:
    - name: "[1/2] checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "[2/2] pr generate"
      shell: bash
      run: |
        destBranch=${{ inputs.dest_branch }}
        sourceBranch=$(git branch --show-current)

        echo "Git tree is being verified from $sourceBranch to $destBranch"
        
        git fetch origin ${destBranch}:${destBranch}
        git log "${destBranch}..${sourceBranch}" --oneline

        echo "PR will be geneated from $sourceBranch to $destBranch"

        python ${{ github.action_path }}/action.py ${destBranch} ${sourceBranch}
        
        # https://stackoverflow.com/questions/77728043/github-composite-action-to-run-python-script-in-repo