# Scan : https://github.com/imantisco/mantisco-github-action/security
# Origin : https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#using-trivy-to-scan-infrastructure-as-code
name: Composition / Test Trivy scan github iac config

inputs:
  hide-progress: 
    description: "디버그 모드에서는 활성화해주세요"
    default: true
    required: true

  format:
    description: "
    보안 레벨: [
       table,     json,       template,
       sarif,     cyclonedx,  spdx,
       spdx-json, github,     cosign-vuln
    ]
    e.g.
    - table
    "
    # default: "sarif"
    required: true

  severity:
    description: "
      보안 레벨: [UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL]
      e.g.
      - UNKNOWN,LOW,MEDIUM
      - LOW,MEDIUM,HIGH
      - MEDIUM,HIGH,CRITICAL
    "
    # default: "CRITICAL"
    required: true

  output_file:
    description: "Output 파일을 입력해주세요."
    # default: "trivy-results.sarif"
    required: true

outputs:
  trivy-result:
    description: "trivy 실행 결과"
    value: ${{ steps.trivy-result.outputs.trivy-result }}
    
runs:
  using: composite
  steps:
    - name: "[1/6] Git 체크아웃"
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "[2/6] Trivy 설치 및 캐시"
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.57.1

    - name: "[3/6] Trivy 실행하기"
      id: trivy-execution
      uses: aquasecurity/trivy-action@0.28.0
      with:
        # exit-code: 1
        scan-type: 'config'
        hide-progress: ${{ inputs.hide-progress }}

        format: ${{ inputs.format }}
        output: ${{ inputs.output_file }}
        severity: ${{ inputs.severity }}

    - name: "[4/6] Trivy 결과 Output에 저장하기"
      id: trivy-result
      shell: bash
      run: |
        OUTPUT_FILE_NAME=${{ inputs.output_file }}
        OUTPUT_FILE=$(cat $OUTPUT_FILE_NAME)

        echo "trivy-result=$(echo $OUTPUT_FILE)" >> $GITHUB_OUTPUT
        # echo "::set-output name=trivy-result::$OUTPUT_FILE"

    - name: "[5/6] Trivy 결과 형태 변환하기"
      id: trivy-result-convert
      shell: bash
      run: |
        echo "Prepared"
    
    - name: "[6/6] Trivy 변환된 결과를 Issue에 게시하기"
      shell: bash
      run: |
        echo "Prepared"

    # github/codeql-action/upload-sarif@v3 is not working
    # - name: "[4/6] Trivy Security Tab에 게시하기"
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: ${{ inputs.output_file }}