# Composite Action : https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
# GitHub Action의 Compsite 액션 지정하기 : https://blog.outsider.ne.kr/1592
# GitHub Workflow 재사용하기 : https://marshallku.com/dev/reuse-github-actions



name: PR Generator

# NEED PERMISSIONS
# permissions:
#   pull-requests: write              # PR 작성 및 수정 권한
#   contents: read                    # 리포지토리 내용 읽기 권한
#   issues: read                      # 이슈 읽기 권한
#   repository-projects: read         # 프로젝트 읽기 권한

runs:
  using: composite
  steps:
    - name: checkout github with fetch-depth as 0
      id: ci/pull_request/pull_request_generator
      uses: actions/checkout@v3
      with:
        fetch-depth: 0