name: Composition / Test Helm Template

input:
  helm_destination:
    description: '경로'
    default: './test'
    required: true

runs:
  using: composite
  steps:
    - name: "[1/4] checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "[2/4] Cache Helm CLI"
      uses: actions/cache@v3
      with:
        path: |
          ~/.helm
          /usr/local/bin/helm
        key: ${{ runner.os }}-helm-get-helm-3
        restore-keys: |
          ${{ runner.os }}-helm-

    - name: "[3/4] Install Helm CLI"
      shell: bash
      run: |
        if ! command -v helm &> /dev/null; then
          echo "Helm not found, installing..."
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
        else
          echo "Helm is cached, skipping installation."
        fi

    - name: "[4/4] Helm Template"
      shell: bash
      run: |
        cd ${{ inputs.helm_destination }}

        set -x
        chmod +x ${{ github.action_path }}/action.sh
        ${{ github.action_path }}/action.sh DEBUG