name: Composition / Test Trivy Scan AWS ECR Resgistry

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-22.04
    
    steps:
      - uses: imantisco/mantisco-github-action/composition/test_trivy_scan_aws_ecr_registry@dev
        with:
          format: "sarif"
          output_file: "trivy-results.sarif"
        env:
          AWS_ECR_IMAGE_REF: nginx
          # AWS_ECR_IMAGE_REF: ${{ secrets.AWS_ECR_IMAGE_REF }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Output
        shell: bash
        run: |
          echo ${{ steps.test_trivy_scan_github_iac_conf.outputs.trivy-result }}