name: Composition / Test Trivy FS(FileSystem)

runs:
  using: composite
  steps:
    - name: "[1/4] checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "[3/4] Install Trivy CLI"
      shell: bash
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.57.1/trivy_0.57.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.57.1_Linux-64bit.deb

        ls
        ls /usr/local/bin | grep trivy