name: Composition / Test Trivy FS(FileSystem)

runs:
  using: composite
  steps:
    - name: "[1/4] Git 체크아웃"
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "[2/4] Trivy CLI 캐시하기"
      uses: actions/cache@v3
      with:
        path: |
          trivy_0.57.1_Linux-64bit.deb
          /usr/bin/trivy
        key: ${{ runner.os }}-trivy-${{ hashFiles('trivy_0.57.1_Linux-64bit.deb') }}
        restore-keys: |
          ${{ runner.os }}-trivy-

    - name: "[3/4] Trivy CLI 설치하기"
      shell: bash
      run: |
        if ! command -v trivy &> /dev/null; then
          echo "[INFO] Trivy CLI가 설치를 시작합니다."

          wget https://github.com/aquasecurity/trivy/releases/download/v0.57.1/trivy_0.57.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.57.1_Linux-64bit.deb
        else
          echo "[INFO] Trivy CLI가 설치되어 있습니다."
        fi

    - name: "[4/4] Trivy FileSystem 감사하기(테스트)"
      shell: bash
      run: |
        trivy fs ./
